<?php
$strings = array(
    'RUBRICA_NOMBRE'=> 'RUBRICA_NOMBRE',
    'RUBRICA_DESCRIPCION'=>'RUBRICA_DESCRIPCION',
    'RUBRICA_NIVELES'=>'RUBRICA_NIVELES',
    'GESTION RUBRICAS'=>'GESTION RUBRICAS'
        )
?>